#数据源配置
spring:
  redis:
    ##redis 单机环境配置
    host: dev.juwins.com
    port: 6379
    password: juwins.com
    database: 0
    ssl: false
    ##redis 集群环境配置
    #cluster:
    #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
    #  commandTimeout: 5000
  datasource:
    #    url: jdbc:mysql://203.125.12.205:23306/house?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    #    username: house
    #    password: House@2020
    url: jdbc:mysql://dev.juwins.com:3060/house?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: house
    password: House@2020
    driver-class-name: com.mysql.cj.jdbc.Driver

#blade配置
blade:
  prop:
    upload-path: D:/image
    #upload-path: /Users/wfc/projects/其他外包项目-2020/新加坡-VR看房系统/git/singaporeHouseManager/VUE-House-Manage/public/
    document-path: /home/test/mcc_site/upload/
    #document-path: /Users/wfc/projects/其他外包项目-2020/新加坡-VR看房系统/git/singaporeHouseManager/VUE-House-Manage/public/
    prefixUrl: http://203.125.12.205:31081
    requestUrl: http://203.125.12.205:31081
    upload-domain: http://mccadmin.dev.yuwuxing.com:18380/
    remote-mode: true
    remote-path: /usr/share/nginx/html
    remote-path-iis: D://iis/html
    log-mode: true
    #邮件相关配置
    mailFrom: noreply@mccsingapore.com.sg
    password_mailFrom: Jingye-1973
    mail_host: smtp.mccsingapore.com.sg
    smtp: smtp
    active_host: localhost
thymeleaf:
  cache: false #关闭缓存
  mode: HTML5 #设置模板类型
  encoding: utf-8  #设置编码
